### ISSUE TITLE
Comment text in appeals from UTRS 1 are missing

### ISSUE THREAD

**Issue by JJMC89** [UTRS2/utrs#214] opened 2020-06-22 03:29 UTC
- Admin comments are not visible, just user and timestamp (even as a tool admin)
- Appeals do not appear when searching by ID or appellant
- Appeals do not appear in the previous appeals section (of 1.8 or 2 appeals)

Example appellant for testing:
- UTRS 2 appeal #31060
- UTRS 1.8 appeals #27118, #27130, #27465, and #27475

**Comment by supertassu** [comment] 2020-06-22 12:03
> * Admin comments are not visible, just user and timestamp (even as a tool admin)

That's a bug. I have a feeling it's caused by
https://github.com/UTRS2/utrs/blob/623dab59ba7b8172bdf79f384160a5ab0c03cbc3/resources/views/appeals/oldappeal.blade.php#L100

having a wrong variable name ([this](https://github.com/UTRS/utrs/blob/42e8e7d98ddd824d47a50a12daee279c46af654b/mysql_schema.sql#L58) suggests it should be `$comment['comment']`). @dqwiki can you confirm this from database?

----

> * Appeals do not appear when searching by ID or appellant
> * Appeals do not appear in the previous appeals section (of 1.8 or 2 appeals)

UTRS 1 appeals shouldn't even have a "Previous appeals" section. I think both of these are considered as "missing features" instead of "bugs" due to the way both of those are stored. I created #216 for the "previous appeals" section, #217 for the search bar and added a note to #152 about old appeals. I'll try to get those fixed in the near future.

**Comment by dqwiki** [comment] 2020-06-24 23:49
> having a wrong variable name ([this](https://github.com/UTRS/utrs/blob/42e8e7d98ddd824d47a50a12daee279c46af654b/mysql_schema.sql#L58) suggests it should be `$comment['comment']`). @dqwiki can you confirm this from database?

Correct.

**Closed as completed** 2020-06-25 12:36 UTC
