### ISSUE TITLE
Possible bug with the UTRS

### ISSUE THREAD

**Issue by lace4shark** [UTRS2/utrs#458] opened 2021-06-30 10:03 UTC
https://en.wikipedia.org/w/index.php?title=User_talk:Deepfriedokra&oldid=1031186239#2_questions_regarding_my_first_attempt_at_getting_an_IP_block_exemption

According to DeepFriedOkra, someone else (including me) have noticed a bug that occurs whenever someone clicks the button and enters information into the form, the form asks for you to input your username, and even if you do this correctly, the admin who reviews the unblock request will not know who the username is. (even though the person correctly supplies the form with their username in the relevant text input box)

**Comment by supertassu** [comment] 2021-07-11 18:21
Unless something is broken, UTRS does display the user name to administrators when appealing IP blocks if the blocked user chose "If you have a user account" when creating the appeal, even if they are appealing an IP block. If "If you DO NOT have a user account" was selected, the user is prompted for the blocked IP address only and a username can't be shown as the system is not aware of it. 

"Possible bugs" are extremely hard to fix as you're even sure what you are fixing, so unless someone manages to find a case where the entered username is somehow not visible to the reviewing administrators when using the "If you have a user account" workflow I don't see any actionables here.

**Comment by JJMC89** [comment] 2021-07-11 19:13
> Unless something is broken, UTRS does display the user name to administrators when appealing IP blocks if the blocked user chose "If you have a user account" when creating the appeal, even if they are appealing an IP block.

I assume that the username is initially recorded (when "Action: create" is the comment). Then it is sometimes changed to the underlying blocked IP (when "Action: changed block information" is the comment), so admins cannot see the initially provided account name.

When I search for IP under account appeals, I shouldn't find IPs as the subject, but there are a significant number of them. The first one is from 2020-05-31.

**Comment by GWHAYWOOD** [comment] 2021-07-12 14:15
See for example

https://utrs-beta.wmflabs.org/public/appeal/view?hash=d9e925a18958674c9dcdbb52e57396f3

Which showed the user name under the first "User" column in the "Admin comments" table until I added a comment.  After I added the comment, the user name changed to the blocked IP range.

The overwhelming impression is of untested prototype code, not fit for use.

**Comment by supertassu** [comment] 2021-07-15 16:55
Ah, thanks. I think this is a bug in the block information verification code, which is supposed to normalize the block target displayed to what MediaWiki thinks it is (for example by converting block IDs to block numbers). It loads block information for the blocked IP address, and then (wrongly) changes the appeal target to the blocked IP/range.

There is a separate database column for the blocked IP/range in cases like these, but it doesn't seem to be displayed anywhere.. Not sure if it should be. :/

> The overwhelming impression is of untested prototype code

That is possible. I have been working to improve code quality since I practically inherited this project a little over a year ago, but haven't been able to touch everything since it is still a volunteer project to everyone involved, and I haven't been particularly motivated to work on it as I don't even use the software myself.

**Comment by SidChat93** [comment] 2021-09-30 04:21
I have used the UTRS 3 times. Never faced the bug.

**Comment by rickrollfan** [comment] 2021-12-08 14:05
for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltasfor yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas

**Comment by skiingguy** [comment] 2021-12-19 14:57
for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltasfor yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas

**Comment by rockandroll111** [comment] 2022-01-16 11:28
for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltasfor yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas

**Comment by sandcastleguy** [comment] 2022-01-17 13:06
for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltasfor yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas

**Comment by hahalol69** [comment] 2022-01-23 13:31
Hi fuckers

**Comment by lolhaha69** [comment] 2022-01-24 13:27
wfffewgeeeewweeg

**Comment by birdisthe** [comment] 2022-01-26 13:28
ggnsgnsnrryryrjtytf

**Comment by ohyeah12345** [comment] 2022-01-31 12:54
hhtgrwwrtggtrtrrt

**Comment by Endymiona** [comment] 2022-02-05 12:34
Hi nigger faggots

**Comment by Endymiona** [comment] 2022-02-13 13:02
Yxxyfyif figoogcoggo

**Comment by dqwiki** [comment] 2022-04-11 17:26
> There is a separate database column for the blocked IP/range in cases like these, but it doesn't seem to be displayed anywhere.. Not sure if it should be. :/

This is exactly by design. We don't want people revealing their IP addresses and connecting them to user accounts essentially leaving the equivalent of a CU record in the appeal.

We could reveal that extra column to CheckUsers, but that's as far as I'd be willing to go for privacy reasons.

**Comment by dqwiki** [comment] 2022-04-22 15:04
I think I know what you were talking about here and it has been fixed in #553

**Closed as completed by dqwiki** 2022-04-22 15:04 UTC
