### ISSUE TITLE
Won't allow comments

### ISSUE THREAD

**Issue by deepfriedokra** [UTRS2/utrs#395] opened 2020-12-12 11:37 UTC
Said to report here. Messages to appellants is working, but not comments to other admins.

**Comment by supertassu** [comment] 2020-12-12 12:04
this might be #394, I'll check in a moment

**Comment by supertassu** [comment] 2020-12-12 12:35
yeah, this is a duplicate of #394. closing in favour of that one

**Closed as completed by supertassu** 2020-12-12 12:35 UTC
Labels: wontfix/duplicate
